/** @type {import('tailwindcss').Config} */
const { fontFamily } = require("tailwindcss/defaultTheme");

module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      helvetica: "'Helvetica Neue', 'sans-serif'",
    },
    fontSize: {
      "4xl": [
        "40px",
        {
          lineHeight: "1.5",
        },
      ],
      "3.8xl": [
        "38px",
        {
          lineHeight: "1.5",
        },
      ],
      "3.5xl": [
        "35px",
        {
          lineHeight: "1.5",
        },
      ],

      "3.2xl": [
        "30px",
        {
          lineHeight: "1.5",
        },
      ],
      "3xl": [
        "28px",
        {
          lineHeight: "1.5",
        },
      ],

      "2.5xl": [
        "26px",
        {
          lineHeight: "1.5",
        },
      ],
      "2xl": ["24px"],
      "22px": ["22px"],
      "xl-alt": ["20px"],
      xl: ["18px"],
      lg: ["16px"],
      15: ["15px"],
      base: ["14px"],
      sm: ["12px"],
      xs: ["10px"],
      xxs: ["8px"],
      xxxs: ["7px"],
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-sora)", "Sora", ...fontFamily.sans],
        mono: ["var(--font-space-mono)", "Space Mono", ...fontFamily.mono],
        avanir: ["var(--font-avanir)", ...fontFamily.sans],
        futora: ["var(--font-futora)", ...fontFamily.sans],
        fondamento: ["var(--font-fondamento)", ...fontFamily.sans],
      },
      fontWeight: {
        normal: "300",
        medium: "400",
        semibold: "600",
        bold: "700",
        extrabold: "800",
      },
      boxShadow: {
        custom: "0px 0px 10px rgba(225, 231, 242, 0.8)",
      },
      colors: {
        blue: {
          DEFAULT: "#1E1E1E",
          disabled: "#CECBF7",
          hover: "#1921C8",
          text: "#0A142F",
          "outline-hover": "#eeedfe",
          50: "#F2F8FF",
          alt: "#70BAF2",
          backdrop: "rgba(255, 255, 255, 0.02)",
          dull: "rgba(84, 68, 242, 0.1)",
          clear: "rgba(84, 68, 242, 0.11)",
          border: "rgba(84, 68, 242, 0.21)",
          textHover: "#9990FA",
          bright: "#1A8DFF",
        },
        grey: {
          DEFAULT: "#ACACAC",
          dark: "#1E1E1E",
          dark2: "#2D2D2D",
          blue: "#54627E",
          alt: "#F4F4F4",
          text: "#47566B",
          text2: "#949494",
          text3: "#A1A9B4",
          text4: "#BBAFAF",
          text5: "#949494",
          text6: "#565656",
          text7: "#6F6F6F",
          white: "#EDEDED",
          white2: "#DEDEDE",
          whitesmoke: "#F6F6F6",
          whitesmoke2: "#E3E3E3",
          whitesmoke3: "#FAFAFA",
          border: "#E1E1E1",
          border2: "rgba(0, 0, 0, 0.1)",
          border3: "#CFC2C2",
          border4: "#D1D5DA",
          border5: "#D2D2D2",
          border6: "#D8D8D8",
          bordercolor: "#EEEEEE",
          borderalt: "#D3D3D3",
          light: "#D0D0D2",
          label: "#6B7188",
          backdrop: "rgba(16, 3, 3, 0.35)",
          ghostwhite: "#f5f6fadc",
          light: "#e1e1e1",
          light2: "#D9D9D9",
          light3: "#A7A7A7",
          light4: "#F5F5F5",
          light8: "#FBFBFB",
          fade: "#8A93A6",
          fadeLight: "#F2F2F2",
          disabled: "#E3E6EA",
          darker: "#101626",
          darkest: "#151515",
          black: "#151718",
          black2: "#222222",
          greyLight: "#d0cfd128",
          greyLight2: "#E0E0E0",
          light10: "#C2C7D6",
          dull: "#F8F8F8",
          skeleton: "#ebebeb",
          white: "rgba(255, 255, 255, 0.8)",
          10: "#6E6E6E",
          15: "rgba(255, 255, 255, 0.15)",
          144: "rgb(142, 142, 144)",
          66: "#2B2B2BA8",
        },
        red: {
          DEFAULT: "#CE051D",
          text: "#F3564D",
          light: "rgba(206, 5, 29, 0.06)",
          light2: "#FDEAEB",
          light3: "#FCF0F1",
          light4: "#FFDBDE",
          light5: "#f2b3b8",
          light6: "#FFEDEF",
          light7: "#FF4D4D",
        },
        purple: {
          DEFAULT: "#EBF1FE",
          light: "#F4F5F9",
        },
        green: {
          light: "#02BA81",
          light2: "#E9FFE9",
          light3: "#73D0AF",
          warning: "#02BA81",
          dark: "#009A49",
        },
        yellow: {
          DEFAULT: "#FFCB00",
          golden: "#F9CB54",
          deep: "#DFB10C",
        },
        transparent: {
          DEFAULT: "transparent",
        },
        black: {
          DEFAULT: "#000000",
          light: "#3D4451",
          fade: "rgba(0, 0, 0, 0.3)",
          text: "#767676",
          1: "#171410",
        },
      },

      height: {
        13: "52px",
      },
      maxWidth: {
        "10%": "10%",
        "15%": "15%",
        "20%": "20%",
        "30%": "30%",
        "35%": "35%",
        "40%": "40%",
        "70%": "70%",
        "75%": "75%",
        "80%": "80%",
        "90%": "90%",
        "9xl": "300rem",
      },
      width: {
        "10%": "10%",
        "15%": "15%",
        "20%": "20%",
        "30%": "30%",
        "35%": "35%",
        "40%": "40%",
        "70%": "70%",
        "75%": "75%",
        "80%": "80%",
        "90%": "90%",
      },
      screens: {
        "4xs": "300px",
        "3xs": "380px",
        "2xs": "475px",
        xs: "540px",
        slg: "910px",
        950: "950px",
        "2lg": "1200px",
      },
      margin: {
        "-85px": "-85px",
        "-60px": "-60px",
      },

      backgroundImage: {
        hero: "url('/iphone_14_pro_space_black_mockup.png')",
        hero_image: "url('/hero-image.jpeg')",
        app_store: "url('/app_store.svg')",
        google_play: "url('/google_play.svg')",
        pattern_bg: "url('/pattern_bg.svg')",
        pattern_bg_2: "url('/pattern_bg_2.svg')",
        iphone_14_one: "url('/iphone_14_one.png')",
        iphone_14_two: "url('/iphone_14_two.png')",
        iphone_14_three: "url('/iphone_14_three.png')",
        iphone_14_vendor_one: "url('/iphone_14_vendor_one.png')",
        iphone_14_vendor_two: "url('/iphone_14_vendor_two.png')",
        iphone_14_vendor_three: "url('/iphone_14_vendor_three.png')",
        pattern_blue_bg: "url('/pattern_blue.svg')",
        "signup-img": "url('/images/signup-img.jpeg')",
        "spring-sale": "url('/images/spring-sale.jpeg')",
        "laroch-img": "url('/images/laroch-img.png')",
        laroch: "url('/images/laroch.jpeg')",
        "beard-man": "url('/images/beard-man.jpeg')",
        biotherm: "url('/images/biotherm.png')",
        clinique: "url('/images/Clinique.svg')",
        neutrogena: "url('/images/Neutrogena.svg')",
        "cerave-img": "url('/images/cerave-logo.png')",
        "cerave-banner": "url('/images/cerave-banner.png')",
      },

      keyframes: {
        slide: {
          "0%": { transform: "translateY(40px)" },
          "100%": { transform: "translateY(50px)" },
        },
      },
      animation: {
        slide: "slide 0.5s forwards",
      },
    },
    minHeight: {
      460: "460px",
      360: "360px",
    },
    minWidth: {
      460: "460px",
      360: "360px",
      930: "930px",
    },
    borderWidth: {
      DEFAULT: "1px",
      "1/2": "0.5px",
    },
  },
  plugins: [],
};
